name: QuietMic
options:
  useBaseInternationalization: true
  bundleIdPrefix: com.williamwagner

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig

packages:
  QuietMicIntents:
    path: QuietMicIntents

settings:
  base: {}

targets:
  QuietMic:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - ios/QuietMic/App
      - ios/QuietMic/Features
    dependencies:
      - package: QuietMicIntents
    frameworks:
      - AppIntents
    postbuildScripts:
      - name: Copy QuietMicIntents Metadata
        script: |
          set -euo pipefail
          SRC="${BUILT_PRODUCTS_DIR}/QuietMicIntents.appintents/Metadata.appintents"
          DEST="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Metadata.appintents"
          if [ -d "$SRC" ]; then
            rsync -a --delete "$SRC/" "$DEST/"
          else
            echo "warning: AppIntents metadata bundle not found at $SRC" >&2
          fi
        shell: /bin/zsh
    resources:
      - ios/QuietMic/Resources
    info:
      path: Configs/QuietMic.Info.plist
      properties:
        NSMicrophoneUsageDescription: "QuietMic records audio locally on-device for quick voice memos"
        UIBackgroundModes: ["audio"]
    entitlements:
      path: Configs/QuietMic.entitlements
      properties: {}
    settings:
      base:
        PRODUCT_NAME: QuietMic
    scheme:
      testTargets:
        - QuietMicTests
        - QuietMicUITests

  QuietMicTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - QuietMicTests
    dependencies:
      - target: QuietMic
    settings:
      base:
        PRODUCT_NAME: QuietMicTests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/QuietMic.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/QuietMic
        BUNDLE_LOADER: $(TEST_HOST)
        STRING_CATALOG_GENERATE_SYMBOLS: false
    scheme: {}

  QuietMicUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - QuietMicUITests
    dependencies:
      - target: QuietMic
    settings:
      base:
        PRODUCT_NAME: QuietMicUITests
        TEST_TARGET_NAME: QuietMic
        STRING_CATALOG_GENERATE_SYMBOLS: false
    scheme: {}
